service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

plugins:
  - serverless-offline
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /saludo
          method: GET