version: '3.8'

services:
  database_parcial_electiva:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    image: parcial_electiva_eam  
    container_name: mysql_parcial_electiva
    restart: always
    ports:
      - "4500:3306"
    volumes:
      - ./Config/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - eam_parcial_electiva

  adminer_electiva:
    image: adminer
    container_name: adminer_parcial_electiva
    restart: always
    ports:
      - "8080:8080"
    networks:
      - eam_parcial_electiva
    depends_on:
      - database_parcial_electiva

networks:
  eam_parcial_electiva:
    driver: bridge